CREATE TABLE "MORNING_ROUTINE_INFO"
   (	"MORNING_ROUTINE_SNO" NUMBER NOT NULL ENABLE,
	"RECORD_DATE" DATE NOT NULL ENABLE,
	"BEDTIME" DATE NOT NULL ENABLE,
	"WAKE_UP_TIME" DATE NOT NULL ENABLE,
	"WALK_YN" CHAR(1) NOT NULL ENABLE,
	"SUCCESS_FAILURE_YN" CHAR(4) NOT NULL ENABLE,
	"NOTE" VARCHAR2(4000) NOT NULL ENABLE,
	"GRATITUDE_JOURNAL" VARCHAR2(4000) NOT NULL ENABLE,
	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MOD_DATE" DATE,
	 CONSTRAINT "MORNING_ROUTINE_INFO_PK" PRIMARY KEY ("MORNING_ROUTINE_SNO")
);

COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.MORNING_ROUTINE_SNO IS '순번(시퀀스: MORNING_ROUTINE_SNO_SEQ)';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.RECORD_DATE IS '기록날짜';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.BEDTIME IS '전날 취침시간';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.WAKE_UP_TIME IS '기상 예정시간';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.WALK_YN IS '기상시간';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.SUCCESS_FAILURE_YN IS '산책여부';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.NOTE IS '비고';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.GRATITUDE_JOURNAL IS '감사일기';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.REG_DATE IS '등록일시';
COMMENT ON COLUMN DEV_01.MORNING_ROUTINE_INFO.MOD_DATE IS '수정일시';

